[project]
name = "task_tracker"
authors = [
    { name = "Sowaan", email = "info@sowaan.com"}
]
description = "An app to track the tasks, comes with a desktop app that will make timesheets and put tasks into timesheets"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
    "pytesseract==0.3.10",
    "opencv-python==4.7.0.68",
    "Pillow==9.5.0",
    "numpy==1.23.5",
    "transformers==4.30.0",
    "torch",
    "openai"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
